"use strict";
const SOURCE_COMMIT="7be9f991aad0deda5b1b873c39bda3ba155ee01d", VERSION="20260731", STORAGE="spritelab-sven-walk-v1";
const frameUrl=n=>`inputs/sven/walk/atlas-original/frame-${String(n).padStart(2,"0")}.png?v=${VERSION}`;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults=()=>({schemaVersion:1,fps:15,loop:true,playing:true,frame:1,direction:"right",variant:"original",compareMode:"fps",order:Array.from({length:24},(_,i)=>i+1),enabled:Array(24).fill(true),durations:Array(24).fill(67),offsets:Array.from({length:24},()=>({x:0,y:0})),baseline:422,background:"checker",zoom:82,onion:{previous:false,next:false,opacity:25},overlays:{ground:true,bounds:false,center:false,canvas:false,filename:false,offset:false}});
let state=load(), analysis, images=[], playClock=performance.now(), pairMode=false, pairStep=0, variantStart=performance.now();
const proposals={original:Array.from({length:24},(_,i)=>i+1),p12:[],p8:[]};
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE));if(v?.schemaVersion===1&&v.order?.length===24)return Object.assign(defaults(),v)}catch(e){console.warn("Ignored invalid SpriteLab project",e)}return defaults()}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
async function boot(){
  analysis=await fetch(`outputs/analysis/sven-walk-analysis.json?v=${VERSION}`).then(r=>r.json()); proposals.p12=analysis.proposals["12"];proposals.p8=analysis.proposals["8"];
  images=await Promise.all(proposals.original.map(n=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=frameUrl(n)})));
  bind(); renderAll(); requestAnimationFrame(tick);
}
function sequence(kind=state.variant){if(kind==="original")return proposals.original;if(kind==="p12")return proposals.p12;if(kind==="p8")return proposals.p8;return state.order.filter(n=>state.enabled[n-1])}
function selectedMetric(){return analysis.frames[state.frame-1]}
function drawSprite(canvas,n,opts={}){const ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;const o=state.offsets[n-1], metric=analysis.frames[n-1], direction=opts.direction||state.direction;
  if(opts.overlays!==false&&(state.onion.previous||state.onion.next)){ctx.save();ctx.globalAlpha=state.onion.opacity/100;for(const other of [state.onion.previous?prevFrame(n):null,state.onion.next?nextFrame(n):null])if(other){const oo=state.offsets[other-1];if(direction==="left"){ctx.save();ctx.translate(canvas.width,0);ctx.scale(-1,1);ctx.drawImage(images[other-1],oo.x,oo.y);ctx.restore()}else ctx.drawImage(images[other-1],oo.x,oo.y)}ctx.restore()}
  ctx.save();if(opts.alpha!=null)ctx.globalAlpha=opts.alpha;if(direction==="left"){ctx.translate(canvas.width,0);ctx.scale(-1,1)}ctx.drawImage(images[n-1],o.x,o.y);ctx.restore();if(opts.overlays===false)return;
  const ov=state.overlays;ctx.save();ctx.lineWidth=1;
  if(ov.ground){ctx.strokeStyle="#e8b252";ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(0,state.baseline+.5);ctx.lineTo(360,state.baseline+.5);ctx.stroke()}
  if(ov.bounds){const b=metric.alphaBounds;ctx.strokeStyle="#75d1d5";ctx.setLineDash([]);ctx.strokeRect(b.x+o.x+.5,b.y+o.y+.5,b.width,b.height)}
  if(ov.center){const c=metric.visualCenter;ctx.strokeStyle="#ff706d";ctx.beginPath();ctx.moveTo(c.x+o.x-7,c.y+o.y);ctx.lineTo(c.x+o.x+7,c.y+o.y);ctx.moveTo(c.x+o.x,c.y+o.y-7);ctx.lineTo(c.x+o.x,c.y+o.y+7);ctx.stroke();ctx.fillStyle="#ff706d";ctx.fillRect(c.x+o.x-2,metric.lowestVisiblePixel+o.y-2,5,5)}
  if(ov.canvas){ctx.strokeStyle="#fff";ctx.strokeRect(.5,.5,359,439)}ctx.fillStyle="#111c";ctx.font="700 12px ui-monospace";if(ov.filename)ctx.fillText(metric.filename,8,18);if(ov.offset)ctx.fillText(`x ${o.x>0?"+":""}${o.x} / y ${o.y>0?"+":""}${o.y}`,8,36);ctx.restore()
}
function tick(now){if(state.playing){const seq=sequence();if(seq.length){const duration=state.compareMode==="duration"&&state.variant!=="manual"?1600/seq.length:(1000/state.fps);if(now-playClock>=duration){let i=seq.indexOf(state.frame);i=i<0?0:i+1;if(i>=seq.length){if(state.loop)i=0;else{state.playing=false;i=seq.length-1}}state.frame=seq[i];playClock=now;renderStage();selectTimeline(false)}}}renderVariants(now);if(pairMode&&now-playClock>260){pairStep^=1;state.frame=pairStep?nextFrame(state.frame):state.frame;playClock=now;renderTransition()}requestAnimationFrame(tick)}
function nextFrame(n){const seq=sequence("manual"),i=seq.indexOf(n);return seq[(i+1+seq.length)%seq.length]||1}
function prevFrame(n){const seq=sequence("manual"),i=seq.indexOf(n);return seq[(i-1+seq.length)%seq.length]||1}
function renderStage(){drawSprite($("#preview"),state.frame);$("#frameBadge").textContent=`FRAME ${String(state.frame).padStart(2,"0")} / 24`;$("#scrubber").value=state.frame;$("#directionLabel").textContent=state.direction==="right"?"SOURCE · RIGHT":"RUNTIME MIRROR · LEFT";$("#playBtn").textContent=state.playing?"❚❚":"▶";$("#playBtn").ariaLabel=state.playing?"Pause":"Play";$("#stage").className=`stage ${state.background}`;$("#preview").style.height=`${state.zoom}%`;$("#variantLabel").textContent=state.variant==="original"?"Original · 24 frames":state.variant==="p12"?"Proposal · 12 frames":state.variant==="p8"?"Proposal · 8 frames":`Manual · ${sequence().length} enabled`;}
function renderTimeline(){const warnings=new Set(analysis.transitions.filter(t=>t.suspicious).flatMap(t=>[t.from,t.to]));$("#timeline").innerHTML=state.order.map(n=>`<button class="frame-card ${n===state.frame?"selected":""} ${state.enabled[n-1]?"":"disabled"} ${warnings.has(n)?"warning":""}" data-frame="${n}" role="option" aria-selected="${n===state.frame}"><canvas width="72" height="88"></canvas><span><b>${String(n).padStart(2,"0")}</b><i>${state.durations[n-1]}ms</i></span></button>`).join("");$$('[data-frame]').forEach(card=>{const n=+card.dataset.frame,c=card.querySelector("canvas"),x=c.getContext("2d");x.imageSmoothingEnabled=false;x.drawImage(images[n-1],0,0,72,88);card.onclick=()=>select(n)});selectTimeline(false)}
function selectTimeline(scroll=true){$$('.frame-card').forEach(c=>c.classList.toggle("selected",+c.dataset.frame===state.frame));const m=selectedMetric();$("#selectedLabel").textContent=`Frame ${String(state.frame).padStart(2,"0")} · ${m.filename}`;$("#duration").value=state.durations[state.frame-1];$("#toggleFrame").textContent=state.enabled[state.frame-1]?"Disable frame":"Enable frame";$("#offsetX").value=state.offsets[state.frame-1].x;$("#offsetY").value=state.offsets[state.frame-1].y;$("#offsetXOut").textContent=`${state.offsets[state.frame-1].x} px`;$("#offsetYOut").textContent=`${state.offsets[state.frame-1].y} px`;if(scroll)$(`[data-frame="${state.frame}"]`)?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"});renderDetail();renderTransition()}
function select(n,scroll=true){state.frame=n;state.playing=false;playClock=performance.now();renderStage();selectTimeline(scroll);save()}
function metric(label,value){return `<div class="metric"><small>${label}</small><strong>${value}</strong></div>`}
function renderDetail(){if(!analysis)return;const m=selectedMetric(),o=state.offsets[state.frame-1];drawSprite($("#detailCanvas"),state.frame);$("#detailTitle").textContent=m.filename;$("#frameMetrics").innerHTML=metric("Canvas",`${m.width} × ${m.height} RGBA`)+metric("Alpha bounds",`${m.alphaBounds.x}, ${m.alphaBounds.y} · ${m.alphaBounds.width}×${m.alphaBounds.height}`)+metric("Lowest pixel",`${m.lowestVisiblePixel}px`)+metric("Visual center",`${m.visualCenter.x}, ${m.visualCenter.y}`)+metric("Silhouette",`${m.silhouetteArea.toLocaleString()} px`)+metric("Current offset",`${o.x}, ${o.y}`)+metric("Duration",`${state.durations[state.frame-1]}ms`)+metric("Enabled",state.enabled[state.frame-1]?"Yes":"No")}
function renderTransition(){if(!analysis)return;const a=state.frame,b=nextFrame(a),t=analysis.transitions.find(x=>x.from===a&&x.to===b)||analysis.transitions[a-1];drawSprite($("#beforeCanvas"),a,{overlays:false});drawSprite($("#afterCanvas"),b,{overlays:false});const c=$("#diffCanvas"),ctx=c.getContext("2d");ctx.clearRect(0,0,360,440);ctx.globalAlpha=.65;ctx.globalCompositeOperation="source-over";ctx.drawImage(images[a-1],0,0);ctx.globalCompositeOperation="difference";ctx.drawImage(images[b-1],0,0);ctx.globalCompositeOperation="source-over";ctx.globalAlpha=1;$("#transitionTitle").textContent=`Frame ${String(a).padStart(2,"0")} → ${String(b).padStart(2,"0")}`;$("#transitionMetrics").innerHTML=metric("Center Δ X",`${t.horizontalCenterMovement>0?"+":""}${t.horizontalCenterMovement}px`)+metric("Center Δ Y",`${t.verticalCenterMovement>0?"+":""}${t.verticalCenterMovement}px`)+metric("Baseline Δ",`${t.baselineMovement>0?"+":""}${t.baselineMovement}px`)+metric("Area change",`${t.silhouetteAreaChangePercent}%`)+metric("Similarity",t.frameSimilarity)+metric("Pixel difference",t.pixelDifference)}
function renderVariants(now=performance.now()){if(!analysis)return;$$('.variant-card').forEach(card=>{const kind=card.dataset.kind,seq=sequence(kind),rate=state.compareMode==="duration"?1600/seq.length:1000/state.fps,n=seq[Math.floor((now-variantStart)/rate)%seq.length],c=card.querySelector("canvas");drawSprite(c,n,{overlays:false,direction:state.direction})})}
function buildVariants(){$("#variantGrid").innerHTML=[["original","Original 24",proposals.original],["p12","12-frame proposal",proposals.p12],["p8","8-frame proposal",proposals.p8],["manual","Current manual",sequence("manual")]].map(([k,title,seq])=>`<button class="variant-card ${state.variant===k?"active":""}" data-kind="${k}"><canvas width="360" height="440"></canvas><h3>${title}</h3><p>${seq.join(" · ")}</p></button>`).join("");$$('.variant-card').forEach(x=>x.onclick=()=>{state.variant=x.dataset.kind;state.frame=sequence()[0];$$('.variant-card').forEach(y=>y.classList.toggle("active",y===x));renderStage();save()})}
function renderFindings(){const near=analysis.nearDuplicates.map(x=>`${x.from}→${x.to}`).join(", ")||"None";const suspicious=analysis.transitions.filter(t=>t.suspicious);$("#findings").innerHTML=`<button class="finding" data-jump="${analysis.likelyContactFrames[0]}"><strong>Likely contact poses</strong><span>Frames ${analysis.likelyContactFrames.join(", ")} · baseline extrema and stability</span></button><button class="finding" data-jump="${analysis.nearDuplicates[0]?.from||1}"><strong>Near-duplicate transition</strong><span>${near} · silhouette overlap ≥ 0.90</span></button><button class="finding warning" data-jump="24"><strong>Loop closure 24 → 1</strong><span>${analysis.transitions[23].verticalCenterMovement}px vertical · ${analysis.transitions[23].frameSimilarity} similarity</span></button>`+suspicious.map(t=>`<button class="finding warning" data-jump="${t.from}" data-transition><strong>Transition ${t.from} → ${t.to}</strong><span>Center Δ ${t.horizontalCenterMovement}, ${t.verticalCenterMovement}px · area ${t.silhouetteAreaChangePercent}%</span></button>`).join("");$$('[data-jump]').forEach(x=>x.onclick=()=>{select(+x.dataset.jump);if(x.hasAttribute("data-transition"))activateTab("transition")})}
function renderAll(){renderStage();renderTimeline();buildVariants();renderFindings();$("#fps").value=state.fps;$("#loop").checked=state.loop;$("#baseline").value=state.baseline;$("#baselineOut").textContent=`${state.baseline} px`;$("#zoom").value=state.zoom;$("#onionOpacity").value=state.onion.opacity;$("#onionOut").textContent=`${state.onion.opacity}%`;$("#onionPrev").checked=state.onion.previous;$("#onionNext").checked=state.onion.next;$$('[data-direction]').forEach(x=>x.classList.toggle("active",x.dataset.direction===state.direction));$$('[data-bg]').forEach(x=>x.classList.toggle("active",x.dataset.bg===state.background));$$('[data-overlay]').forEach(x=>x.checked=!!state.overlays[x.dataset.overlay]);$$('[data-compare]').forEach(x=>x.classList.toggle("active",x.dataset.compare===state.compareMode))}
function activateTab(id){$$('.tool-tabs button').forEach(x=>x.classList.toggle("active",x.dataset.tab===id));$$('.tool-panel').forEach(x=>x.classList.toggle("active",x.id===id));if(id==="transition")renderTransition();if(id==="variants")buildVariants()}
function changeOffset(axis,value){state.offsets[state.frame-1][axis]=+value;renderStage();selectTimeline(false);save()}
function bind(){
  $("#playBtn").onclick=()=>{state.playing=!state.playing;pairMode=false;playClock=performance.now();renderStage();save()};$("#prevBtn").onclick=()=>select(prevFrame(state.frame));$("#nextBtn").onclick=()=>select(nextFrame(state.frame));$("#scrubber").oninput=e=>select(+e.target.value,false);$("#fps").onchange=e=>{state.fps=Math.max(1,Math.min(60,+e.target.value||15));save()};$("#resetFps").onclick=()=>{$("#fps").value=state.fps=15;save()};$("#loop").onchange=e=>{state.loop=e.target.checked;save()};
  $$('[data-direction]').forEach(x=>x.onclick=()=>{state.direction=x.dataset.direction;renderAll();save()});$$('[data-bg]').forEach(x=>x.onclick=()=>{state.background=x.dataset.bg;renderAll();save()});$("#zoom").oninput=e=>{state.zoom=+e.target.value;renderStage();save()};$("#gameSize").onclick=()=>{$("#zoom").value=state.zoom=48;renderStage();save()};$("#inspectBtn").onclick=()=>{document.body.classList.toggle("inspecting");$("#inspectBtn").textContent=document.body.classList.contains("inspecting")?"Exit":"Enlarge"};
  $("#toggleFrame").onclick=()=>{state.enabled[state.frame-1]=!state.enabled[state.frame-1];renderTimeline();buildVariants();save()};$("#moveLeft").onclick=()=>move(-1);$("#moveRight").onclick=()=>move(1);$("#duration").onchange=e=>{state.durations[state.frame-1]=Math.max(16,+e.target.value||67);renderTimeline();save()};$("#restoreOrder").onclick=()=>{state.order=proposals.original.slice();renderTimeline();buildVariants();save()};$("#restoreTiming").onclick=()=>{state.durations.fill(67);renderTimeline();save()};
  $("#offsetX").oninput=e=>changeOffset("x",e.target.value);$("#offsetY").oninput=e=>changeOffset("y",e.target.value);$("#resetSelected").onclick=()=>{state.offsets[state.frame-1]={x:0,y:0};renderAll();save()};$("#resetOffsets").onclick=()=>{state.offsets=defaults().offsets;renderAll();save()};$("#autoAlign").onclick=()=>{analysis.frames.forEach((m,i)=>state.offsets[i].y=state.baseline-m.lowestVisiblePixel);renderAll();save()};$("#baseline").oninput=e=>{state.baseline=+e.target.value;$("#baselineOut").textContent=`${state.baseline} px`;renderStage();save()};
  $("#onionOpacity").oninput=e=>{state.onion.opacity=+e.target.value;$("#onionOut").textContent=`${state.onion.opacity}%`;save()};["Prev","Next"].forEach(k=>$("#onion"+k).onchange=e=>{state.onion[k.toLowerCase()]=e.target.checked;save()});$$('[data-overlay]').forEach(x=>x.onchange=()=>{state.overlays[x.dataset.overlay]=x.checked;renderStage();renderDetail();save()});
  $$('.tool-tabs button').forEach(x=>x.onclick=()=>activateTab(x.dataset.tab));$("#repeatTransition").onclick=()=>{pairMode=!pairMode;state.playing=false;$("#repeatTransition").textContent=pairMode?"Stop repeat":"Repeat pair";playClock=performance.now()};$$('[data-compare]').forEach(x=>x.onclick=()=>{state.compareMode=x.dataset.compare;renderAll();save()});$("#restartVariants").onclick=()=>{variantStart=performance.now()};$$('[data-export]').forEach(x=>x.onclick=()=>doExport(x.dataset.export));$("#resetProject").onclick=()=>{if(confirm("Reset every SpriteLab edit?")){state=defaults();save();location.reload()}};$("#importProject").onchange=importProject;
  let drag=null;$("#preview").onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,start:{...state.offsets[state.frame-1]}};e.target.setPointerCapture(e.pointerId)};$("#preview").onpointermove=e=>{if(!drag)return;const scale=$("#preview").getBoundingClientRect().width/360;changeOffset("x",Math.round(drag.start.x+(e.clientX-drag.x)/scale));changeOffset("y",Math.round(drag.start.y+(e.clientY-drag.y)/scale))};$("#preview").onpointerup=()=>drag=null;
}
function move(delta){const i=state.order.indexOf(state.frame),j=Math.max(0,Math.min(23,i+delta));if(i===j)return;state.order.splice(i,1);state.order.splice(j,0,state.frame);renderTimeline();buildVariants();save();$(`[data-frame="${state.frame}"]`).scrollIntoView({inline:"center"})}
function blobDownload(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function projectData(){return {...state,project:"Sven — Walk — Atlas Original",atlasCommit:SOURCE_COMMIT,exportedAt:new Date().toISOString()}}
function metadata(){return {schemaVersion:1,character:"Sven",animation:"walk",sourceDirection:"right",runtimeMirroring:true,fps:state.fps,loop:state.loop,enabledFrameOrder:state.order.filter(n=>state.enabled[n-1]),perFrameDurations:state.durations,xOffsets:state.offsets.map(o=>o.x),yOffsets:state.offsets.map(o=>o.y),canvas:{width:360,height:440},sharedGroundAnchor:state.baseline,originalFrameCount:24,originalCycleDurationSeconds:1.6,originalAtlasPath:"assets/characters/sven/walk-right",atlasCommit:SOURCE_COMMIT}}
function jsonDownload(data,name){blobDownload(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),name)}
function normalizedCanvas(n){const c=document.createElement("canvas");c.width=360;c.height=440;const x=c.getContext("2d"),o=state.offsets[n-1];x.drawImage(images[n-1],o.x,o.y);return c}
function canvasDownload(c,name){c.toBlob(b=>blobDownload(b,name),"image/png")}
function doExport(kind){if(kind==="project")return jsonDownload(projectData(),"sven-walk.spritelab.json");if(kind==="metadata")return jsonDownload(metadata(),"sven-walk.atlas.json");if(kind==="frame")return canvasDownload(normalizedCanvas(state.frame),`frame-${String(state.frame).padStart(2,"0")}-normalized.png`);if(kind==="allFrames"){sequence("manual").forEach((n,i)=>setTimeout(()=>canvasDownload(normalizedCanvas(n),`frame-${String(n).padStart(2,"0")}-normalized.png`),i*120));return}if(kind==="sheet"){const seq=sequence("manual"),cols=Math.ceil(Math.sqrt(seq.length)),rows=Math.ceil(seq.length/cols),c=document.createElement("canvas");c.width=cols*360;c.height=rows*440;seq.forEach((n,i)=>c.getContext("2d").drawImage(normalizedCanvas(n),(i%cols)*360,Math.floor(i/cols)*440));return canvasDownload(c,"sven-walk-spritesheet.png")}if(kind==="preview"){const a=document.createElement("a");a.href="outputs/previews/sven-walk-24.gif?v="+VERSION;a.download="sven-walk-preview.gif";a.click();return}const text=`const SVEN_WALK = ${JSON.stringify(metadata(),null,2)};\n// Mirror at runtime: sprite.style.transform = facing === "left" ? "scaleX(-1)" : "none";`;$("#snippet").hidden=false;$("#snippet").textContent=text;navigator.clipboard?.writeText(text)}
async function importProject(e){try{const v=JSON.parse(await e.target.files[0].text());if(v.schemaVersion!==1||v.order?.length!==24)throw Error("Unsupported or invalid SpriteLab project");state=Object.assign(defaults(),v);save();renderAll();alert("Project imported.")}catch(err){alert(err.message)}e.target.value=""}
boot().catch(e=>{console.error(e);document.body.innerHTML=`<main><h1>SpriteLab could not load</h1><p>${e.message}</p></main>`});
