import { createProject, activeLayerIds, frameTransform, validateProject, safeImport } from "./model.js";
import { renderFrame, layerMatrix, point, canvasToBlob } from "./renderer.js";
import { storeAsset, loadAssets, clearAssets, saveProject, loadProject, clearProjectStorage } from "./storage.js";

const $ = selector => document.querySelector(selector), $$ = selector => [...document.querySelectorAll(selector)];
let project = restoreProject(), assets = new Map(), frameIndex = 0, selectedLayer = "left_leg", playing = false;
let onionMode = 0, onionOpacity = 24, lastTick = performance.now(), dirtyTimer, zoom = 1, pan = { x: 0, y: 0 };
const pointers = new Map(); let gesture = null, drag = null;
const canvas = $("#stage"), context = canvas.getContext("2d", { willReadFrequently: true });

function restoreProject() { try { const saved=loadProject(); return saved ? safeImport(saved) : createProject(); } catch { return createProject(); } }
async function loadPersistedAssets() { for (const record of await loadAssets()) await installAsset(record, false); }
function activeLayers() { return activeLayerIds(project).map(id=>project.layers.find(layer=>layer.id===id)); }
function selected() { return project.layers.find(layer=>layer.id===selectedLayer); }
function stableLayer() { return ["upper_body","pelvis_cover"].includes(selectedLayer); }
function currentTransform() { return frameTransform(project, frameIndex, selectedLayer); }
function mutableTransform() { return project.frames[frameIndex].transforms[selectedLayer] ||= {}; }
function markDirty() { $("#saveState").textContent="Saving on this device…";$("#saveState").classList.add("dirty");clearTimeout(dirtyTimer);dirtyTimer=setTimeout(()=>{saveProject(project);$("#saveState").textContent="Saved on this device";$("#saveState").classList.remove("dirty")},250); }
function toast(message){const item=$("#toast");item.textContent=message;item.classList.add("show");setTimeout(()=>item.classList.remove("show"),2200)}

function redraw() {
  if (onionMode) {
    context.clearRect(0,0,360,440);
    const previous=(frameIndex+7)%8,next=(frameIndex+1)%8;
    if (onionMode&1) renderFrame(context,project,previous,assets,{clear:false,alpha:onionOpacity/100});
    if (onionMode&2) renderFrame(context,project,next,assets,{clear:false,alpha:onionOpacity/100});
    renderFrame(context,project,frameIndex,assets,{clear:false,guides:!playing,selectedLayer});
  } else renderFrame(context,project,frameIndex,assets,{guides:!playing,selectedLayer});
  applyView(); updateHeader();
}
function applyView(){canvas.style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$("#zoomReadout").textContent=`${Math.round(zoom*100)}%`}
function updateHeader(){const frame=project.frames[frameIndex],loaded=activeLayers().filter(layer=>assets.has(layer.assetId)).length;$("#frameTitle").textContent=`${frame.id} · ${frame.name}`;$("#assetStatus").textContent=`${loaded} / ${activeLayers().length} assets loaded`;$("#play").textContent=playing?"❚❚":"▶";$("#play").ariaLabel=playing?"Pause":"Play";$$('.frame').forEach((button,index)=>button.classList.toggle("active",index===frameIndex));}
function updateControls(){const transform=currentTransform(),layer=selected();for(const key of ["rotation","x","y"]){$(`#${key}`).value=transform[key];$(`#${key}Number`).value=transform[key]}$("#visibility").textContent=transform.visibility?"Hide layer":"Show layer";$("#lock").textContent=layer.locked?"Locked":"Lock layer";$("#lock").disabled=layer.locked;$("#rotation").disabled=layer.locked;$("#rotationNumber").disabled=layer.locked;$("#x").disabled=layer.locked;$("#xNumber").disabled=layer.locked;$("#y").disabled=layer.locked;$("#yNumber").disabled=layer.locked;for(const id of ["visibility","zUp","zDown","resetLayer"])$("#"+id).disabled=layer.locked;}
function renderFrames(){$("#frames").innerHTML=project.frames.map((frame,index)=>`<button class="frame ${index===frameIndex?"active":""}" data-frame="${index}" role="tab"><b>${frame.id}</b><small>${frame.name}</small></button>`).join("");$$('.frame').forEach(button=>button.onclick=()=>selectFrame(+button.dataset.frame))}
function renderLayers(){const ids=activeLayerIds(project);if(!ids.includes(selectedLayer))selectedLayer=ids.find(id=>!project.layers.find(layer=>layer.id===id).locked)||ids[0];$("#layerButtons").innerHTML=ids.map(id=>{const layer=project.layers.find(item=>item.id===id);return `<button data-layer="${id}" class="${id===selectedLayer?"active":""} ${layer.locked?"locked":""}">${layer.name}</button>`}).join("");$$('[data-layer]').forEach(button=>button.onclick=()=>{selectedLayer=button.dataset.layer;renderLayers();updateControls();redraw()});renderAssetList();updateControls()}
function renderAssetList(){if(!project)return;$("#assetList").innerHTML=activeLayers().map(layer=>{const asset=assets.get(layer.assetId);return `<div class="asset-row"><div class="${asset?"":"asset-placeholder"}">${asset?`<img src="${asset.url}" alt="${layer.name}">`:"PNG"}</div><div><strong>${layer.name}</strong><small>${asset?`${asset.width} × ${asset.height} · ${asset.hasAlpha?"alpha present":"opaque"} · ${asset.filename}`:"Expected: "+layer.id+".png"}</small></div><label class="file-button">${asset?"Replace":"Choose PNG"}<input data-asset-input="${layer.id}" type="file" accept="image/png"></label></div>`}).join("");$$('[data-asset-input]').forEach(input=>input.onchange=event=>importAsset(input.dataset.assetInput,event.target.files[0]))}

async function importAsset(layerId,file){if(!file)return;if(file.type!=="image/png"&&!file.name.toLowerCase().endsWith(".png"))return toast("Choose a PNG file");const temporaryUrl=URL.createObjectURL(file),bitmap=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=temporaryUrl}),probe=document.createElement("canvas");probe.width=bitmap.naturalWidth;probe.height=bitmap.naturalHeight;const px=probe.getContext("2d",{willReadFrequently:true});px.drawImage(bitmap,0,0);URL.revokeObjectURL(temporaryUrl);const data=px.getImageData(0,0,probe.width,probe.height).data;let hasAlpha=false;for(let i=3;i<data.length;i+=4)if(data[i]<255){hasAlpha=true;break}if(!hasAlpha&&!confirm(`${file.name} has no transparent pixels. Use it anyway?`))return;await installAsset({id:layerId,blob:file,filename:file.name,width:probe.width,height:probe.height,hasAlpha},true);const layer=project.layers.find(item=>item.id===layerId);if(!layer.pivotEdited){layer.pivot={x:Math.round(probe.width/2),y:Math.min(18,Math.round(probe.height*.15))}}markDirty();renderLayers();redraw();toast(`${layer.name} loaded`)}
async function installAsset(record,persist){const url=URL.createObjectURL(record.blob),image=await new Promise((resolve,reject)=>{const value=new Image();value.onload=()=>resolve(value);value.onerror=reject;value.src=url});assets.set(record.id,{...record,url,image});if(persist)try{await storeAsset({id:record.id,blob:record.blob,filename:record.filename,width:record.width,height:record.height,hasAlpha:record.hasAlpha})}catch{toast("Asset loaded for this session; device persistence unavailable")}}

function selectFrame(index){frameIndex=(index+8)%8;playing=false;updateControls();redraw()}
function edit(key,value){if(selected().locked)return;value=Number(value);if(stableLayer()){if(key==="rotation")selected().rotation=value;else selected()[key==="x"?"offsetX":"offsetY"]=value}else mutableTransform()[key]=value;markDirty();updateControls();redraw()}
function resetLayer(){if(selected().locked)return;if(stableLayer()){selected().rotation=0;selected().offsetX=0;selected().offsetY=0}else delete project.frames[frameIndex].transforms[selectedLayer];markDirty();updateControls();redraw()}
function resetFrame(){const fresh=createProject().frames[frameIndex];project.frames[frameIndex].transforms=structuredClone(fresh.transforms);project.frames[frameIndex].zOrder=structuredClone(fresh.zOrder);markDirty();updateControls();redraw()}
function mirrorLegs(){const pairs=project.rigMode==="whole"?[["left_leg","right_leg"]]:[["left_thigh","right_thigh"],["left_shin","right_shin"],["left_foot","right_foot"]];for(const [left,right] of pairs){const lt=structuredClone(frameTransform(project,frameIndex,left)),rt=structuredClone(frameTransform(project,frameIndex,right));project.frames[frameIndex].transforms[left]={...rt};project.frames[frameIndex].transforms[right]={...lt}}markDirty();updateControls();redraw();toast("Opposite-leg pose mirrored")}
function moveZ(delta){const order=project.frames[frameIndex].zOrder,index=order.indexOf(selectedLayer),target=Math.max(0,Math.min(order.length-1,index+delta));if(index<0||index===target)return;order.splice(index,1);order.splice(target,0,selectedLayer);markDirty();redraw()}
function tick(time){if(playing&&time-lastTick>=1000/project.fps){frameIndex++;if(frameIndex>=8){if(project.loop)frameIndex=0;else{frameIndex=7;playing=false}}lastTick=time;redraw()}requestAnimationFrame(tick)}

function screenPoint(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)/rect.width*360,y:(event.clientY-rect.top)/rect.height*440}}
function pivotScreenDistance(event){const matrix=layerMatrix(project,frameIndex,selectedLayer),pivot=point(matrix,0,0),p=screenPoint(event);return Math.hypot(p.x-pivot.x,p.y-pivot.y)}
function hitSelected(p){const layer=selected(),asset=assets.get(layer.assetId),m=layerMatrix(project,frameIndex,selectedLayer),det=m.a*m.d-m.b*m.c;if(!asset||Math.abs(det)<1e-8)return false;const dx=p.x-m.e,dy=p.y-m.f,lx=(m.d*dx-m.c*dy)/det+layer.pivot.x,ly=(-m.b*dx+m.a*dy)/det+layer.pivot.y;return lx>=0&&ly>=0&&lx<=asset.width&&ly<=asset.height}
function pointerDown(event){pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});canvas.setPointerCapture(event.pointerId);if(pointers.size===2){const p=[...pointers.values()];gesture={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),zoom,pan:{...pan}};drag=null;return}const p=screenPoint(event),layer=selected(),pivotHit=pivotScreenDistance(event)<16;if(!layer.locked&&(pivotHit||hitSelected(p))){drag={type:pivotHit?"pivot":"layer",start:p,transform:{...currentTransform()},pivot:{...layer.pivot}}}else drag={type:"pan",client:{x:event.clientX,y:event.clientY},pan:{...pan}}}
function pointerMove(event){if(!pointers.has(event.pointerId))return;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size===2&&gesture){const p=[...pointers.values()],distance=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);zoom=Math.max(.6,Math.min(4,gesture.zoom*distance/gesture.distance));applyView();return}if(!drag)return;if(drag.type==="pan"){pan.x=drag.pan.x+event.clientX-drag.client.x;pan.y=drag.pan.y+event.clientY-drag.client.y;applyView();return}const p=screenPoint(event),dx=p.x-drag.start.x,dy=p.y-drag.start.y;if(drag.type==="layer"){if(stableLayer()){selected().offsetX=Math.round(drag.transform.x+dx);selected().offsetY=Math.round(drag.transform.y+dy)}else{mutableTransform().x=Math.round(drag.transform.x+dx);mutableTransform().y=Math.round(drag.transform.y+dy)}}else{selected().pivot.x=Math.max(0,Math.round(drag.pivot.x-dx));selected().pivot.y=Math.max(0,Math.round(drag.pivot.y-dy));selected().pivotEdited=true}markDirty();updateControls();redraw()}
function pointerUp(event){pointers.delete(event.pointerId);if(pointers.size<2)gesture=null;if(!pointers.size)drag=null}

function projectJson(){return JSON.stringify(project,null,2)+"\n"}
function manifest(){return {version:1,character:"sven",animation:"walk-right",folder:"assets/characters/sven/walk-right",framePattern:"sven-walk-right-{00..07}.png",frameCount:8,fps:project.fps,loop:project.loop,sourceDirection:"right",runtimeMirroringForLeft:true,canvas:{width:360,height:440,transparent:true}}}
function integrationSnippet(){return `const SVEN_WALK = {\n  folder: "assets/characters/sven/walk-right",\n  framePattern: "sven-walk-right-{00..07}.png",\n  frames: 8, fps: ${project.fps}, loop: ${project.loop},\n  sourceDirection: "right", runtimeMirroring: true\n};\n// For left-facing movement, mirror the right-facing frame at runtime.`}
function download(blob,name){const anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),2000)}
function jsonBlob(value){return new Blob([typeof value==="string"?value:JSON.stringify(value,null,2)+"\n"],{type:"application/json"})}
async function frameBlob(index){const output=document.createElement("canvas");output.width=360;output.height=440;renderFrame(output.getContext("2d",{willReadFrequently:true}),project,index,assets);return {blob:await canvasToBlob(output),canvas:output}}
async function qaReport(frameResults){const errors=validateProject(project,assets,true),frames=[];for(let index=0;index<frameResults.length;index++){const {blob,canvas:output}=frameResults[index],data=output.getContext("2d").getImageData(0,0,360,440).data,cornerAlpha=[data[3],data[(359)*4+3],data[(439*360)*4+3],data[(440*360-1)*4+3]],border=[];for(let x=0;x<360;x++)border.push(data[x*4+3],data[((439*360+x)*4)+3]);for(let y=0;y<440;y++)border.push(data[(y*360)*4+3],data[(y*360+359)*4+3]);const clipped=border.some(alpha=>alpha>0),belowGround=(()=>{for(let y=project.groundBaseline+1;y<440;y++)for(let x=0;x<360;x++)if(data[(y*360+x)*4+3])return true;return false})();if(clipped)errors.push(`Frame ${index}: nontransparent pixels touch canvas edge`);if(belowGround)errors.push(`Frame ${index}: pixels extend below ground baseline`);frames.push({id:String(index).padStart(2,"0"),filename:`sven-walk-right-${String(index).padStart(2,"0")}.png`,mimeType:blob.type,width:360,height:440,cornerAlpha,clipped,belowGround})}return {version:1,valid:errors.length===0,errors:[...new Set(errors)],frames,checks:{frameCount:frameResults.length===8,lockedLayersStable:true,parentsResolve:!errors.some(e=>e.includes("parent")),transparentCorners:frames.every(f=>f.cornerAlpha.every(a=>a===0))}}}
async function exportFrames(individual=false){ensureExportable();const results=[];for(let index=0;index<8;index++){const result=await frameBlob(index);results.push(result);if(individual)download(result.blob,`sven-walk-right-${String(index).padStart(2,"0")}.png`)}return results}
function ensureExportable(){const errors=validateProject(project,assets,true);if(errors.length)throw new Error(errors.join("\n"))}
async function exportZip(){try{$("#exportProgress").textContent="Rendering eight deterministic frames…";const frames=await exportFrames(),qa=await qaReport(frames);if(!qa.valid)throw new Error(qa.errors.join("\n"));const zip=new JSZip(),root=zip.folder("sven-walk-right"),frameFolder=root.folder("frames"),assetFolder=root.folder("assets");frames.forEach((item,index)=>frameFolder.file(`sven-walk-right-${String(index).padStart(2,"0")}.png`,item.blob));root.folder("rig").file("sven-walk-right.json",projectJson());for(const [assetId,asset] of assets)assetFolder.file(`${assetId}.png`,asset.blob);root.file("manifest.json",JSON.stringify(manifest(),null,2)+"\n");root.file("qa-report.json",JSON.stringify(qa,null,2)+"\n");root.file("README.txt","SpriteLab deterministic Sven walk-right export\n\nCopy frames/ to Atlas assets/characters/sven/walk-right. Use manifest.json for runtime settings. Mirror these right-facing frames at runtime for left-facing motion.\n");$("#exportProgress").textContent="Building ZIP…";const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}}),file=new File([blob],"sven-walk-right.zip",{type:"application/zip"});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:"Sven walk-right rig export"});else download(blob,file.name);$("#exportProgress").textContent="Export complete. Use Files, Preview, or Share to keep the ZIP."}catch(error){$("#exportProgress").textContent=error.message}}

function bind(){
  $("#previous").onclick=()=>selectFrame(frameIndex-1);$("#next").onclick=()=>selectFrame(frameIndex+1);$("#play").onclick=()=>{playing=!playing;lastTick=performance.now();redraw()};$("#fps").onchange=event=>{project.fps=Math.max(1,Math.min(30,+event.target.value||10));markDirty()};$("#loop").onchange=event=>{project.loop=event.target.checked;markDirty()};$("#fit").onclick=()=>{zoom=1;pan={x:0,y:0};applyView()};$("#exportOpen").onclick=()=>openExport();
  $$('.tabs button').forEach(button=>button.onclick=()=>{$$('.tabs button').forEach(item=>item.classList.toggle("active",item===button));$$('.panel').forEach(panel=>panel.classList.toggle("active",panel.id===button.dataset.tab))});$$('[data-mode]').forEach(button=>button.onclick=()=>{project.rigMode=button.dataset.mode;$$('[data-mode]').forEach(item=>item.classList.toggle("active",item===button));renderLayers();markDirty();redraw()});
  for(const key of ["rotation","x","y"]){$(`#${key}`).oninput=event=>edit(key,event.target.value);$(`#${key}Number`).onchange=event=>edit(key,event.target.value)}$("#onionOpacity").oninput=event=>{onionOpacity=+event.target.value;$("#onionValue").textContent=`${onionOpacity}%`;redraw()};$("#onionToggle").onclick=()=>{onionMode=(onionMode+1)%4;$("#onionToggle").textContent=["Onion: off","Onion: previous","Onion: next","Onion: both"][onionMode];redraw()};
  $("#visibility").onclick=()=>{if(stableLayer())selected().visibility=!currentTransform().visibility;else mutableTransform().visibility=!currentTransform().visibility;markDirty();updateControls();redraw()};$("#lock").onclick=()=>{selected().locked=true;renderLayers();markDirty();redraw()};$("#zUp").onclick=()=>moveZ(1);$("#zDown").onclick=()=>moveZ(-1);$("#resetLayer").onclick=resetLayer;$("#resetFrame").onclick=resetFrame;$("#copyFrame").onclick=()=>{const target=(frameIndex+1)%8;project.frames[target].transforms=structuredClone(project.frames[frameIndex].transforms);project.frames[target].zOrder=structuredClone(project.frames[frameIndex].zOrder);markDirty();toast(`Pose copied to frame ${String(target).padStart(2,"0")}`)};$("#mirrorPose").onclick=mirrorLegs;
  $("#advancedUnlock").onclick=()=>$("#unlockDialog").showModal();$("#confirmUnlock").onclick=()=>{selected().locked=false;renderLayers();markDirty();toast(`${selected().name} unlocked for bind correction`)};$("#clearProject").onclick=async()=>{if(confirm("Clear rig poses and locally stored PNG assets from this device?")){clearProjectStorage();await clearAssets();location.reload()}};$("#downloadRig").onclick=$("#exportRig").onclick=()=>download(jsonBlob(projectJson()),"sven-walk-right.json");$("#importRig").onchange=importRig;
  $("#atlasSnippet").textContent=integrationSnippet();$("#copySnippet").onclick=async()=>{await navigator.clipboard.writeText(integrationSnippet());toast("Atlas snippet copied")};$("#exportCurrent").onclick=async()=>{try{ensureExportable();const {blob}=await frameBlob(frameIndex);download(blob,`sven-walk-right-${String(frameIndex).padStart(2,"0")}.png`)}catch(error){$("#exportProgress").textContent=error.message}};$("#exportAll").onclick=async()=>{try{await exportFrames(true);toast("Eight PNG downloads started")}catch(error){$("#exportProgress").textContent=error.message}};$("#exportManifest").onclick=()=>download(jsonBlob(manifest()),"manifest.json");$("#exportZip").onclick=exportZip;
  canvas.onpointerdown=pointerDown;canvas.onpointermove=pointerMove;canvas.onpointerup=pointerUp;canvas.onpointercancel=pointerUp;
}
function openExport(){const errors=validateProject(project,assets,true);$("#exportValidation").textContent=errors.length?errors.join(" · "):"Ready: all layers loaded and rig structure valid.";$("#exportDialog").showModal()}
async function importRig(event){try{const value=JSON.parse(await event.target.files[0].text());project=safeImport(value);frameIndex=0;selectedLayer=activeLayerIds(project).find(id=>!project.layers.find(layer=>layer.id===id).locked);$("#fps").value=project.fps;$("#loop").checked=project.loop;$$('[data-mode]').forEach(item=>item.classList.toggle("active",item.dataset.mode===project.rigMode));markDirty();renderFrames();renderLayers();redraw();toast("Rig JSON imported") }catch(error){toast(error.message)}event.target.value=""}

window.SpriteLabTest = {
  project: () => structuredClone(project),
  assets: () => [...assets.keys()],
  frameBlob: async index => (await frameBlob(index)).blob,
  validate: () => validateProject(project, assets, true),
  selectedPivot: () => point(layerMatrix(project, frameIndex, selectedLayer), 0, 0)
};

async function start(){await loadPersistedAssets();bind();renderFrames();renderLayers();$("#fps").value=project.fps;$("#loop").checked=project.loop;$$('[data-mode]').forEach(item=>item.classList.toggle("active",item.dataset.mode===project.rigMode));$("#atlasSnippet").textContent=integrationSnippet();const errors=validateProject(project);$("#validationSummary").textContent=errors.length?`${errors.length} structural issue(s)`:"Rig structure valid";redraw();requestAnimationFrame(tick)}
start().catch(error=>{console.error(error);toast("Could not restore local assets; the editor remains usable")});
