import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {ROLES,ROLE_LABELS,assetWorldTransform,transformPoint,defaultParentId,createViewport,documentToScreen,screenToDocument,zoomAtPoint,normalizedPivot,rectFromPoints,polygonContains,alphaBounds,paddedBounds,roleAvailable,createProject,duplicateFrame,serializeProject,createManifest,ARTWORK_DEFAULT_TOOL,artworkToolAfter,isPolygonTap,secondPointerState,anchorDelta,hasAnchorDrift,copyAssetPose,LEG_ROLES,JOINT_SIZES,REPAIR_SHAPES,legChainForRole,resolveLegChain,jointLocalFromWorld,jointWorldPosition,setJoint,upsertJointCover,setJointCoverColor,resetJointCover,removeJointCover,coverRenderOrder,moveAssetLayer,createDemoWalkState,repairsFor,addRepair,setRepairPoint,setRepairColor,deleteRepair,repairWorldPosition,repairFrameOverride,setRepairFrameOffset,resetRepairFrameOffset,assetContainsWorldPoint,repairHitTest,normalizeProject} from '../../studio/model.js';
test('screen/document transforms round trip',()=>{const v={scale:2,offsetX:10,offsetY:-4},p={x:7,y:9};assert.deepEqual(screenToDocument(v,documentToScreen(v,p)),p)});
test('zoom remains anchored around point',()=>{const v={scale:1,offsetX:0,offsetY:0},s={x:50,y:60},before=screenToDocument(v,s);zoomAtPoint(v,s,2);assert.deepEqual(screenToDocument(v,s),before)});
test('normalized pivot clamps',()=>assert.deepEqual(normalizedPivot(60,-2,100,100),{space:'asset-normalized',x:.6,y:0}));
test('rectangle extraction coordinates normalize',()=>assert.deepEqual(rectFromPoints({x:9,y:8},{x:2,y:3}),{x:2,y:3,width:7,height:5}));
test('polygon rasterization',()=>{const p=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}];assert.equal(polygonContains(p,5,5),true);assert.equal(polygonContains(p,15,5),false)});
test('alpha bounds finds visible pixels',()=>{const d=new Uint8ClampedArray(4*4*4);d[(2*4+1)*4+3]=255;d[(3*4+2)*4+3]=1;assert.deepEqual(alphaBounds(d,4,4),{x:1,y:2,width:2,height:2})});
test('crop padding clamps to canvas',()=>assert.deepEqual(paddedBounds({x:1,y:1,width:3,height:3},6,6,4),{x:0,y:0,width:6,height:6}));
test('roles are unique',()=>assert.equal(roleAvailable([{id:'a',role:'left_leg'}],'left_leg'),false));
test('frame duplication is isolated',()=>{const p=createProject();p.frames[0].assetOverrides.a={x:1};const copy=duplicateFrame(p.frames[0],1);copy.assetOverrides.a.x=9;assert.equal(p.frames[0].assetOverrides.a.x,1);assert.notEqual(copy.id,p.frames[0].id)});
test('patch lists duplicate independently',()=>{const p=createProject();p.frames[0].patches.push({id:'p',x:4,y:5});const copy=duplicateFrame(p.frames[0],1);copy.patches[0].x=8;assert.equal(p.frames[0].patches[0].x,4);assert.deepEqual(copy.patches[0],{id:'p',x:8,y:5})});
test('serialization removes runtime images and manifest describes archive',()=>{const p=createProject('QA');p.rigAssets.push({id:'a',image:{},role:'left_leg'});const clean=serializeProject(p);assert.equal('image' in clean.rigAssets[0],false);assert.equal(createManifest(p).entrypoints.rig,'data/rig.json')});
test('new projects start with an eight-frame timeline',()=>assert.equal(createProject().frames.length,8));
test('segmented leg roles and readable labels are available',()=>{const expected={left_upper_leg:'Left upper leg',left_lower_leg:'Left lower leg',right_upper_leg:'Right upper leg',right_lower_leg:'Right lower leg'};for(const [role,label] of Object.entries(expected)){assert.ok(ROLES.includes(role));assert.equal(ROLE_LABELS[role],label)}});
test('Artwork role selector renders readable segmented-leg options',()=>{const html=readFileSync(new URL('../../studio/index.html',import.meta.url),'utf8');for(const [role,label] of Object.entries({left_upper_leg:'Left upper leg',left_lower_leg:'Left lower leg',right_upper_leg:'Right upper leg',right_lower_leg:'Right lower leg'}))assert.match(html,new RegExp(`<option value="${role}">${label}</option>`))});
test('lower legs default to their matching upper leg when present',()=>assert.equal(defaultParentId([{id:'upper',role:'left_upper_leg'}],'left_lower_leg'),'upper'));
test('child inherits parent translation and rotation while retaining local rotation',()=>{const assets=[{id:'upper',position:{x:0,y:0},pivot:{x:0,y:0},width:10,height:10},{id:'lower',parentId:'upper',position:{x:10,y:0},pivot:{x:0,y:0},width:10,height:10}],frame={assetOverrides:{upper:{x:5,y:0,rotation:90},lower:{rotation:30}}};const upper=assetWorldTransform(assets,frame,'upper'),lower=assetWorldTransform(assets,frame,'lower');assert.deepEqual(Object.values(transformPoint(upper,{x:10,y:0})).map(Math.round),[5,10]);assert.deepEqual(Object.values(transformPoint(lower,{x:10,y:0})).map(Math.round),[5,10]);const lowerTip=transformPoint(lower,{x:20,y:0});assert.ok(Math.abs(lowerTip.x-0)<1e-9);assert.ok(Math.abs(lowerTip.y-(10+Math.cos(Math.PI/6)*10))<1e-9)});
test('lower-leg rotation does not affect its upper-leg parent',()=>{const assets=[{id:'upper',position:{x:0,y:0},pivot:{x:0,y:0},width:10,height:10},{id:'lower',parentId:'upper',position:{x:10,y:0},pivot:{x:0,y:0},width:10,height:10}],frame={assetOverrides:{lower:{rotation:90}}};assert.deepEqual(transformPoint(assetWorldTransform(assets,frame,'upper'),{x:10,y:0}),{x:10,y:0});assert.deepEqual(Object.values(transformPoint(assetWorldTransform(assets,frame,'lower'),{x:20,y:0})).map(Math.round),[10,10])});
test('serialization preserves segmented role, parent, pivot, and frame data',()=>{const p=createProject();p.rigAssets.push({id:'lower',role:'left_lower_leg',parentId:'upper',pivot:{x:.5,y:.1},image:{}});p.frames[0].assetOverrides.lower={rotation:25};const clean=serializeProject(p);assert.deepEqual(clean.rigAssets[0],{id:'lower',role:'left_lower_leg',parentId:'upper',pivot:{x:.5,y:.1}});assert.equal(clean.frames[0].assetOverrides.lower.rotation,25)});
test('assets from older projects without parent metadata remain roots',()=>{const asset={id:'legacy',position:{x:3,y:4},pivot:{x:.5,y:.5},width:10,height:10};const point=transformPoint(assetWorldTransform([asset],{assetOverrides:{}},asset.id),{x:3,y:4});assert.deepEqual(point,{x:3,y:4})});

test('Artwork defaults and completed interactions return to Navigate',()=>{assert.equal(ARTWORK_DEFAULT_TOOL,'navigate');for(const action of ['enter','cancel','complete','create'])assert.equal(artworkToolAfter(action,'select'),'navigate');assert.equal(artworkToolAfter('activate','erase'),'erase')});
test('second pointer cancels an uncommitted rectangle for navigation',()=>assert.deepEqual(secondPointerState(),{cancelUncommittedRectangle:true,navigation:true}));
test('polygon taps and drags are discriminated by movement',()=>{assert.equal(isPolygonTap({x:1,y:1},{x:5,y:4}),true);assert.equal(isPolygonTap({x:1,y:1},{x:20,y:1}),false)});
test('anchor delta and drift thresholds use world transforms',()=>{const assets=[{id:'root',position:{x:0,y:0},pivot:{x:0,y:0},width:10,height:10}],previous={assetOverrides:{}},current={assetOverrides:{root:{x:1,y:1,rotation:.5}}};const delta=anchorDelta(assets,previous,current,'root');assert.ok(Math.abs(delta.x-1)<1e-9);assert.ok(Math.abs(delta.y-1)<1e-9);assert.ok(Math.abs(delta.rotation-.5)<1e-9);assert.equal(hasAnchorDrift(delta),false);assert.equal(hasAnchorDrift({...delta,x:1.01}),true)});
test('copying pose changes only the anchor override and preserves hierarchy metadata',()=>{const previous={assetOverrides:{upper:{x:4,y:5,rotation:8},lower:{rotation:20}}},current={assetOverrides:{upper:{x:10,y:11,rotation:1,zIndex:3},lower:{rotation:30}}},assets=[{id:'upper',parentId:null},{id:'lower',parentId:'upper'}];copyAssetPose(previous,current,'upper');assert.deepEqual(current.assetOverrides.upper,{x:4,y:5,rotation:8,zIndex:3});assert.deepEqual(current.assetOverrides.lower,{rotation:30});assert.equal(assets[1].parentId,'upper')});
test('legacy frames without compare editor fields remain serializable',()=>{const project=createProject();delete project.editor;assert.doesNotThrow(()=>serializeProject(project));assert.equal('editor' in serializeProject(project),false)});


test('Head is an optional normal role with readable label and upper-body default parent',()=>{assert.ok(ROLES.includes('head'));assert.equal(ROLE_LABELS.head,'Head');assert.equal(defaultParentId([{id:'body',role:'upper_body'}],'head'),'body');assert.equal(defaultParentId([],'head'),null)});
test('Head serialization preserves hierarchy, pivot, z order and frame transform',()=>{const p=createProject();p.rigAssets.push({id:'h',role:'head',parentId:'b',pivot:{x:.5,y:.9},position:{x:1,y:2},zIndex:8,image:{}});p.frames[0].assetOverrides.h={x:3,rotation:4,zIndex:9};const clean=serializeProject(p);assert.equal(clean.rigAssets[0].role,'head');assert.equal(clean.rigAssets[0].parentId,'b');assert.deepEqual(clean.frames[0].assetOverrides.h,{x:3,rotation:4,zIndex:9})});
test('leg chains resolve only supported matching upper and lower roles',()=>{const assets=[{id:'u',role:'left_upper_leg'},{id:'l',role:'left_lower_leg'}];assert.deepEqual(resolveLegChain(assets,'left_lower_leg'),{side:'left',upper:assets[0],lower:assets[1]});assert.equal(legChainForRole('head'),null);assert.equal(LEG_ROLES.length,4)});
test('joint coordinates round trip through hierarchy world transforms',()=>{const assets=[{id:'u',role:'left_upper_leg',position:{x:10,y:20},pivot:{x:0,y:0},width:20,height:40}],frame={assetOverrides:{u:{x:15,y:25,rotation:30}}},local={x:4,y:7};const world=transformPoint(assetWorldTransform(assets,frame,'u'),{x:14,y:27});const result=jointLocalFromWorld(assets,frame,'u',world);assert.ok(Math.abs(result.x-local.x)<1e-9);assert.ok(Math.abs(result.y-local.y)<1e-9);assert.deepEqual(jointWorldPosition(assets,frame,{assetId:'u',...local}),world)});
test('one cover per chain rebuilds at automatic medium position and color',()=>{const p=createProject(),u={id:'u',role:'left_upper_leg'},l={id:'l',role:'left_lower_leg'};p.rigAssets=[u,l];setJoint(p,'u',{x:4,y:5});const first=upsertJointCover(p,'left','#AABBCC');first.offset={x:9,y:8};first.size='large';const second=upsertJointCover(p,'left','#112233');assert.equal(Object.keys(p.jointCovers).length,1);assert.equal(first===second,false);assert.deepEqual(second,{side:'left',jointAssetId:'u',offset:{x:0,y:0},size:'medium',color:'#112233',colorMode:'automatic'});assert.deepEqual(JOINT_SIZES,{small:10,medium:16,large:22,xl:30})});
test('cover manual color, automatic color, reset and removal are deterministic',()=>{const p=createProject();p.rigAssets=[{id:'u',role:'right_upper_leg'},{id:'l',role:'right_lower_leg'}];setJoint(p,'u',{x:1,y:2});const c=upsertJointCover(p,'right');setJointCoverColor(p,'right','#ABCDEF');assert.equal(c.colorMode,'manual');setJointCoverColor(p,'right','#123456',true);assert.equal(c.colorMode,'automatic');c.offset={x:5,y:6};resetJointCover(p,'right');assert.deepEqual(c.offset,{x:0,y:0});assert.equal(removeJointCover(p,'right'),true);assert.deepEqual(p.joints.right,{assetId:'u',x:1,y:2})});
test('cover ordering stays immediately behind its chain and normal layers move persistently',()=>{const p=createProject();p.rigAssets=[{id:'body',role:'upper_body',zIndex:0},{id:'u',role:'left_upper_leg',zIndex:1},{id:'l',role:'left_lower_leg',zIndex:2},{id:'head',role:'head',zIndex:3}];setJoint(p,'u',{x:0,y:0});upsertJointCover(p,'left');assert.deepEqual(coverRenderOrder(p,p.frames[0]),['joint-cover:left','body','u','l','head']);assert.equal(moveAssetLayer(p,'u',1),true);assert.deepEqual(coverRenderOrder(p,p.frames[0]),['joint-cover:left','body','l','u','head']);assert.deepEqual([...p.rigAssets].sort((a,b)=>a.zIndex-b.zIndex).map(a=>a.id),['body','l','u','head'])});
test('legacy projects without joint metadata serialize unchanged and demo state is isolated',()=>{const p=createProject();delete p.joints;delete p.jointCovers;const before=structuredClone(p),demo=createDemoWalkState();demo.progress=.75;demo.direction='left';assert.deepEqual(serializeProject(p),before);assert.equal(p.activeFrame,0);assert.equal(p.frames.length,8)});

test('repairs are capped at two per leg and keep editable appearance state',()=>{const p=createProject(),asset={id:'u',role:'left_upper_leg',width:20,height:40,position:{x:0,y:0},pivot:{x:0,y:0}};p.rigAssets=[asset];const first=addRepair(p,'u','#AABBCC'),second=addRepair(p,'u');assert.equal(addRepair(p,'u'),null);assert.equal(repairsFor(p,'left').length,2);setRepairPoint(p,'left',first.id,'u',{x:3,y:4});first.size='xl';first.shape='capsule';setRepairColor(p,'left',first.id,'#123456');assert.deepEqual(first.point,{x:3,y:4});assert.equal(first.size,'xl');assert.equal(first.shape,'capsule');assert.equal(first.colorMode,'manual');setRepairColor(p,'left',first.id,'#abcdef',true);assert.equal(first.colorMode,'automatic');assert.deepEqual(REPAIR_SHAPES,['round','oval','capsule']);assert.equal(deleteRepair(p,'left',second.id),true)});
test('all repairs render below every normal cutout regardless of layer moves',()=>{const p=createProject();p.rigAssets=[{id:'u',role:'left_upper_leg',width:10,height:10,zIndex:1},{id:'l',role:'left_lower_leg',width:10,height:10,zIndex:0},{id:'body',role:'upper_body',zIndex:2}];const a=addRepair(p,'u'),b=addRepair(p,'l');assert.deepEqual(coverRenderOrder(p,p.frames[0]),[`repair:left:${a.id}`,`repair:left:${b.id}`,'l','u','body']);moveAssetLayer(p,'body',-1);assert.deepEqual(coverRenderOrder(p,p.frames[0]).slice(0,2),[`repair:left:${a.id}`,`repair:left:${b.id}`])});

test('repair base position and frame offsets are independent',()=>{const p=createProject(),a={id:'u',role:'right_lower_leg',width:30,height:40,position:{x:10,y:20},pivot:{x:0,y:0}};p.rigAssets=[a];const repair=addRepair(p,a.id);repair.point={x:4,y:5};assert.equal(repairFrameOverride(p.frames[0],repair.id),null);setRepairFrameOffset(p.frames[0],repair.id,3,-2);assert.deepEqual(repair.point,{x:4,y:5});assert.deepEqual(repairFrameOverride(p.frames[0],repair.id),{x:3,y:-2});assert.deepEqual(repairWorldPosition(p.rigAssets,p.frames[0],repair),{x:17,y:23});resetRepairFrameOffset(p.frames[0],repair.id);assert.equal(repairFrameOverride(p.frames[0],repair.id),null)});
test('duplicate frames copy repair offsets while blank frames do not inherit them',()=>{const p=createProject();setRepairFrameOffset(p.frames[0],'repair',7,8);const copy=duplicateFrame(p.frames[0],1),blank=p.frames[1];copy.repairOverrides.repair.x=9;assert.equal(p.frames[0].repairOverrides.repair.x,7);assert.deepEqual(blank.repairOverrides,{});assert.deepEqual(copy.repairOverrides.repair,{x:9,y:8})});
test('deleting a repair removes stale overrides from every frame',()=>{const p=createProject(),a={id:'u',role:'left_lower_leg',width:20,height:20};p.rigAssets=[a];const repair=addRepair(p,a.id);for(const frame of p.frames)setRepairFrameOffset(frame,repair.id,1,2);deleteRepair(p,'left',repair.id);assert.ok(p.frames.every(frame=>!(repair.id in frame.repairOverrides)))});
test('old projects normalize missing repair override maps safely',()=>{const p=createProject();delete p.frames[0].repairOverrides;const normalized=normalizeProject(p);assert.deepEqual(normalized.frames[0].repairOverrides,{});assert.deepEqual(serializeProject(normalized).frames[0].repairOverrides,{})});
test('repair hit testing uses rendered overrides and a mobile-sized target',()=>{const p=createProject(),a={id:'u',role:'right_upper_leg',width:20,height:20,position:{x:0,y:0},pivot:{x:0,y:0}};p.rigAssets=[a];const repair=addRepair(p,a.id);repair.point={x:5,y:5};setRepairFrameOffset(p.frames[0],repair.id,10,0);assert.equal(repairHitTest(p,p.frames[0],{x:15,y:5},1)?.repair.id,repair.id);assert.equal(repairHitTest(p,p.frames[0],{x:60,y:5},1),null)});
test('transformed asset hit testing inverts parent and child world transforms',()=>{const assets=[{id:'parent',position:{x:0,y:0},pivot:{x:0,y:0},width:10,height:10},{id:'child',parentId:'parent',position:{x:10,y:0},pivot:{x:0,y:0},width:20,height:10}],frame={assetOverrides:{parent:{rotation:90},child:{rotation:30}}},visible=transformPoint(assetWorldTransform(assets,frame,'child'),{x:20,y:5});assert.equal(assetContainsWorldPoint(assets,frame,'child',visible),true);assert.equal(assetContainsWorldPoint(assets,frame,'child',{x:100,y:100}),false)});
